models/ssh_keys.py
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

from settings import db
from models.instance import Instance

instance_obj = Instance()


class SSHKeys(db.Model):
    __tablename__ = 'ssh_keys'
    __table_args__ = {'extend_existing': True}

    # ssh_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    ssh_key_name = db.Column(db.String(), primary_key=True)
    ssh_key_value = db.Column(db.String())
    ssh_key_format = db.Column(db.String())

    def add_ssh_key_value(self, key_name, key_value, key_format):
        self.ssh_key_name = key_name
        self.ssh_key_value = key_value
        self.ssh_key_format = key_format
        row = db.session.merge(self)
        db.session.add(row)
        db.session.commit()

    def get_ssh_key_names(self):
        ssh_keys = set({})
        instances_list = instance_obj.get_all_instances_from_db()
        for instance in instances_list:
            ssh_keys.add(instance['KeyName'])
        return list(ssh_keys)

    def get_ssh_keys_from_db(self):
        all_keys_list = []
        remaining_keys_list = []
        key_names = self.get_ssh_key_names()
        all_ssh_keys = db.session.query(SSHKeys)
        for key in all_ssh_keys:
            keys_dict = {
                # "KeyId": key.ssh_id,
                "KeyName": key.ssh_key_name,
                "KeyValue": key.ssh_key_value,
                "KeyFormat": key.ssh_key_format
            }
            all_keys_list.append(keys_dict)
            if not key.ssh_key_value:
                if key in key_names:
                    key_names.remove(key)
        remaining_keys_list = [{"KeyName": key} for key in key_names]
        return remaining_keys_list, all_keys_list

    def get_key_by_name(self, key_name):
        row = SSHKeys.query.filter_by(ssh_key_name=key_name).first()
        key_dict = {
            "KeyName": row.ssh_key_name,
            "KeyValue": row.ssh_key_value,
            "keyFormat": row.ssh_key_format
        }
        return key_dict

    def delete_key(self, key_id):
        db.session.query(SSHKeys).filter(SSHKeys.ssh_key_name == key_id).delete()
        db.session.commit()

models/user.py
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

from settings import db, bcrypt
from config import DevelopmentConfig
import jwt
import datetime


class User(db.Model):
    __tablename__ = 'users'
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(), nullable=False)
    password = db.Column(db.String(), nullable=False)
    admin = db.Column(db.Boolean, default=False)

    def get_all_users(self):
        users_list = []
        all_users = db.session.query(User)
        users_list = [{"Id": user.id,
                       "Name": user.name}
                      for user in all_users if not user.admin]
        return users_list

    def add_user(self, username, password, admin=False):
        new_user = User(
            name=username,
            password=bcrypt.generate_password_hash(
                password,
                DevelopmentConfig().BCRYPT_LOG_ROUNDS
            ).decode('utf-8'),
            admin=admin
        )
        try:
            db.session.add(new_user)
            db.session.commit()
        except Exception as db_exceptions:
            print(db_exceptions)

    def encode_auth_token(self, user_id):
        """
        Generates the Auth Token
        :return: string
        """
        try:
            payload = {
                'exp': datetime.datetime.utcnow() + datetime.timedelta(days=1, seconds=0),
                'iat': datetime.datetime.utcnow(),
                'sub': user_id
            }
            return jwt.encode(
                payload,
                DevelopmentConfig().SECRET_KEY,
                algorithm='HS256'
            )
        except Exception as token_exception:
            return token_exception

    @staticmethod
    def decode_auth_token(auth_token):
        """
        Validates the auth token
        :param auth_token:
        :return: integer|string
        """
        try:
            payload = jwt.decode(auth_token, DevelopmentConfig().SECRET_KEY)
            is_blacklisted_token = BlacklistToken.check_blacklist(auth_token)
            if is_blacklisted_token:
                return 'Token blacklisted. Please log in again.'
            return payload['sub']
        except jwt.ExpiredSignatureError:
            return 'Signature expired. Please log in again.'
        except jwt.InvalidTokenError:
            return 'Invalid token. Please log in again.'

    @staticmethod
    def validate_token(token, user_id):
        token_user_id = User.decode_auth_token(token)
        return user_id == token_user_id


class BlacklistToken(db.Model):
    """
    Token Model for storing JWT tokens
    """
    __tablename__ = 'blacklist_tokens'
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    token = db.Column(db.String(500), unique=True, nullable=False)
    blacklisted_on = db.Column(db.DateTime, nullable=False)

    def __init__(self, token):
        self.token = token
        self.blacklisted_on = datetime.datetime.now()

    def __repr__(self):
        return '<id: token: {}'.format(self.token)

    @staticmethod
    def check_blacklist(auth_token):
        # check whether auth token has been blacklisted
        res = BlacklistToken.query.filter_by(token=str(auth_token)).first()
        return res

auth.py
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

from settings import bcrypt, db
from models.user import User
from flask import make_response, Blueprint, render_template, request, redirect, url_for

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

user_obj = User()


@auth_bp.route('/')
def auth():
    return render_template('login.html')


@auth_bp.route('/signin', methods=['POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        try:
            # get user from db
            user = db.session.query(User).filter(User.name == username).first()
            if user:
                auth_token = user_obj.encode_auth_token(user.id)
                if bcrypt.check_password_hash(user.password, password):
                    if user.admin:
                        resp = make_response(redirect(url_for('admin.get_admin')))
                        resp.set_cookie("auth_token", auth_token)
                        return resp
                    resp = make_response(redirect(url_for('user.user')))
                    resp.set_cookie("auth_token", auth_token)
                    return resp
                return redirect(url_for('auth.auth'))
            resp = make_response(redirect(url_for('auth.auth')))
            return resp
        except Exception as login_exception:
            print(login_exception)
            resp = make_response(redirect(url_for('auth.auth')))
            return resp
    return render_template('login.html')

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="../static/images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../static/css/main.css">
	<!--===============================================================================================-->
</head>

<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(../static/images/bg-01.jpg);">
					<span class="login100-form-title-1">
						Sign In
					</span>
				</div>
				<form class="login100-form validate-form" method="post" action="{{ url_for('auth.login') }}">
					
					

					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" id="username" required placeholder="Enter username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" required name="password" id="password" placeholder="Enter password">
						<span class="focus-input100"></span>
					</div>

					<div class="flex-sb-m w-full p-b-30">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>
						
						<div>
							<a href="#" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn">
						<button type="submit" value="login" class="login100-form-btn">
							Login
						</button>
					</div>
				</form>
			</div>
		</div>

	</div>
	<!--===============================================================================================-->
	<script src="../static/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="../static/vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
	<script src="../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../static/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="../static/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../static/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script src="../static/vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
	<script src="../static/js/main.js"></script>

</body>

</html>

templates/template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="../static/vendor/bootstrap/css/bootstrap.min.css">
</head>

<body>

    <div class="container">
            <h4>Bootstrap Snipp for Datatable</h4>

    </div>


    <script src="../static/vendor/bootstrap/js/popper.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="../static/js/main.js"></script>

</body>

</html>